Added nutrition subtopic to allow nutrition fact-related queries
Group-16-COSC-310/grocery-chat-bot pull request #16
Opened 2022-03-09 22:31 UTC by paulgray01

added nutrition values to mock product data and added match pattern and message handler for nutrition queries

2022-03-09 23:42 UTC, SanaBob approved these changes
lgtm

2022-03-10 00:26 UTC, thuanGIT commented
New PR on `product_store_query`

2022-03-10 00:41 UTC, SanaBob commented
added unit test
fixed database

2022-03-10 01:10 UTC, thuanGIT commented on app/products/database.py
> +                calories INT NOT NULL,
There is no need for nutrition facts to be NOT NULL as they might be missing.

2022-03-10 01:16 UTC, thuanGIT commented on app/products/product_info.py
> +            r"(calories|protein|carbs|carbohydrates|sugar|fat|nutrition|nutritional)", re.IGNORECASE)
A nice to have is to handle questions like "Does this bread make me gain weight?"

2022-03-10 01:17 UTC, thuanGIT commented on test/test_product_info.py
> +class TestNutritionInfo:
Should add a case where the handler fails to ensure it does not give answers for nothing.

2022-03-11 01:51 UTC, thuanGIT commented on test/test_product_info.py
> +class TestNutritionInfo:
@SanaBob

2022-03-11 06:46 UTC, thuanGIT commented
@paulgray01 @SanaBob The other team wants to talk to you to migrate to use DialogFlow for NLP instead of regex. So we will have this PR as pending until the discussion is resolved.

2022-03-15 06:49 UTC, SanaBob commented
Added endpoint for Diagflow integration

2022-03-15 23:12 UTC, thuanGIT commented on app/products/product_info.py
> +        intent = intent[8:] # hardcoded to filter intent: product-<intent> Ex. product-price -> intent = price
You can use String.index() or String.split() for more flexible handling.

2022-03-15 23:21 UTC, thuanGIT requested changes
With new implementation with Dialogflow, we need to redesign our internal bot framework. The current new method names can be quite easy to be misunderstood.

We will resolve this in our next meeting.

2022-03-15 23:21 UTC, thuanGIT commented on app/products/product_info.py
> +        for prod in MOCK_PRODUCT_DATA:
Please use `execute_query()` to search for product. This method does a linear scan, which is very expensive,

2022-03-18 00:15 UTC, thuanGIT approved these changes

2022-03-18 00:18 UTC, merged