Update/readme update
Group-16-COSC-310/grocery-chat-bot pull request #17
Opened 2022-03-10 00:26 UTC by SanaBob

+ TOC
+ Test
+ API

2022-03-10 00:36 UTC, thuanGIT commented on README.md
> +We are using pytest for all of our tests. Our test cases can be found in the `test` folder.
`pytest` should be highlighted for easy lookup.

2022-03-10 00:56 UTC, paulgray01 commented on README.md
might be missing an "or" after "information"

2022-03-10 00:57 UTC, paulgray01 commented on README.md
> +**Make sure to import the correctly, as the API is not imported by default, and is dependent on your project's file hierarchy.**
missing "API" after "the"

2022-03-10 00:57 UTC, paulgray01 commented on README.md
> +The database api also allows queries straight from the database.
maybe capitalize api here

2022-03-10 01:02 UTC, paulgray01 commented on README.md
>  This mini-bot will handle any question related to product price, stock, and store information. The bot first determines what topic is of interest (product or store information) and breaks the user's
add nutrition, so "...any question related to product price, stock, nutrition, and store information."

2022-03-10 01:05 UTC, thuanGIT requested changes

2022-03-10 01:05 UTC, thuanGIT commented on README.md
> +### Store Info Bot API
Since the API is separated from the bot, removing the word `Bot` would be clearer that user is not using the bot.

2022-03-10 01:05 UTC, thuanGIT commented on README.md
> +### Product Info Bot API
Same here to remove `Bot`

2022-03-10 01:08 UTC, thuanGIT commented
Also as @paulgray01 pointed out, we need to add a `New features` sections for this README.

2022-03-10 06:38 UTC, SanaBob commented on README.md
> +- intentDetectionTest
I changed it in documentation, make sure to change it in the test @nganphan123 @SanjanaCode

2022-03-11 01:51 UTC, thuanGIT approved these changes

2022-03-15 23:24 UTC, thuanGIT requested changes
Class and method names are being changed in other PRs so we need to accommodate those changes.

2022-03-16 18:46 UTC, paulgray01 commented on README.md
> +from app.products.database import SQLiteDatabase, DatabaseType
SQLiteDatabase was renamed to Database

2022-03-16 18:47 UTC, paulgray01 commented on README.md
> +db = SQLiteDatabase(DatabaseType.MEMORY)
SQLiteDatabase was renamed to Database

2022-03-16 20:06 UTC, paulgray01 commented on README.md
> +# returns list: [OrderedDict([('id', '4011'), ('name', 'banana'), ('names', 'bananas'), ('price', 0.67), ('price_scale', 'per kg'), ('in_stock', True)])]
list needs nutrition info now

2022-03-18 00:58 UTC, paulgray01 approved these changes

2022-03-18 06:30 UTC, thuanGIT reviewed
Need changes after API discussion. If not, it looks good.

2022-03-18 22:58 UTC, merged