Docs
Group-16-COSC-310/grocery-chat-bot pull request #28
Opened 2022-03-18 22:59 UTC by SanaBob

Documentation (Readme) update

2022-03-18 23:05 UTC, paulgray01 approved these changes

2022-03-19 00:00 UTC, SanjanaCode approved these changes

2022-03-19 00:34 UTC, thuanGIT commented
@SanaBob Please change the base branch to `dev`. We then make the final PR to main.

2022-03-19 00:59 UTC, nganphan123 approved these changes

2022-03-19 01:09 UTC, thuanGIT requested changes
Need to add valid uri for screenshots.

2022-03-19 01:37 UTC, SanaBob commented
![image](https://user-images.githubusercontent.com/77403071/159101722-ab6406c4-1e91-4c76-9a00-80ca45760b45.png)

2022-03-19 01:41 UTC, thuanGIT approved these changes

2022-03-19 01:45 UTC, merged